data:
  batch_size: 8
  device: '0'
  epochs: 100
  imgsz: 640
  yaml_path: dataset/data.yaml
model:
  name: yolov8s.pt
  pretrained: true
training:
  amp: true
  artifact_alias: latest
  bbox_interval: -1
  box: 0.7
  cache: false
  close_mosaic: 10
  cls: 0.3
  cos_lr: true
  dataloader: auto
  deterministic: false
  dfl: 1.5
  dropout: 0.0
  exist_ok: true
  export_after_train: true
  export_formats:
  - onnx
  - torchscript
  fraction: 1.0
  freeze: null
  kobj: 1.0
  label_smoothing: 0.0
  linear_lr: false
  local_rank: -1
  lr0: 0.0005
  lrf: 0.0001
  mask_ratio: 4
  momentum: 0.937
  name: wildlife_detection_v2
  nbs: 64
  optimizer: AdamW
  overlap_mask: true
  patience: 50
  plots: true
  pose: 12.0
  pretrained: true
  profile: false
  project: results
  quad: false
  rect: false
  resume: false
  save: true
  save_period: 10
  seed: 42
  single_cls: false
  upload_dataset: false
  val: true
  verbose: true
  warmup_bias_lr: 0.01
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  weight_decay: 0.0005
  workers: 4
